DISCORD_TOKEN = "YOUR_DISCORD_BOT_TOKEN"
TELEGRAM_TOKEN = "YOUR_TELEGRAM_BOT_TOKEN"

ADMINS = {
    "discord": {ADMINISTRATOR_ID, ADMINISTRATOR_ID},
    "telegram": {ADMINISTRATOR_ID, ADMINISTRATOR_ID}
}
