"""
Utility script to migrate from EXTRA_BRIDGES to the new BRIDGES format.
Run this once to generate a new config file with converted bridges.
"""

import json
import os
from collections import defaultdict

def migrate_extra_bridges_to_new_format():
    # Import your existing configuration
    from config import DISCORD_CHANNEL_IDS, TELEGRAM_TARGETS, EXTRA_BRIDGES
    
    # Start with the main bridge
    new_bridges = [
        {
            "name": "Main Bridge",
            "discord_channels": DISCORD_CHANNEL_IDS,
            "telegram_targets": TELEGRAM_TARGETS
        }
    ]
    
    # Group extra bridges by telegram chat+topic
    bridge_groups = defaultdict(list)
    
    for bridge in EXTRA_BRIDGES:
        key = (bridge["telegram_chat_id"], bridge.get("telegram_topic_id"))
        bridge_groups[key].append(bridge["discord_channel_id"])
    
    # Create a new bridge for each group
    for idx, ((chat_id, topic_id), discord_channels) in enumerate(bridge_groups.items()):
        new_bridge = {
            "name": f"Bridge Group {idx+1}",
            "discord_channels": discord_channels,
            "telegram_targets": [{"chat_id": chat_id, "topic_id": topic_id}]
        }
        new_bridges.append(new_bridge)
    
    # Also create 1-to-1 bridges for backward compatibility
    for idx, bridge in enumerate(EXTRA_BRIDGES):
        new_bridge = {
            "name": f"Legacy Bridge {idx+1}",
            "discord_channels": [bridge["discord_channel_id"]],
            "telegram_targets": [
                {
                    "chat_id": bridge["telegram_chat_id"],
                    "topic_id": bridge.get("telegram_topic_id")
                }
            ]
        }
        new_bridges.append(new_bridge)
    
    # Generate the new configuration
    output = "# Generated by migration script\n\n"
    output += f"DISCORD_TOKEN = \"{os.environ.get('DISCORD_TOKEN', '')}\"\n"
    output += f"TELEGRAM_TOKEN = \"{os.environ.get('TELEGRAM_TOKEN', '')}\"\n\n"
    
    # Add legacy config for backward compatibility
    output += "# Legacy configuration (kept for backward compatibility)\n"
    output += f"DISCORD_CHANNEL_IDS = {json.dumps(DISCORD_CHANNEL_IDS, indent=4)}\n\n"
    output += f"TELEGRAM_TARGETS = {json.dumps(TELEGRAM_TARGETS, indent=4)}\n\n"
    output += f"EXTRA_BRIDGES = {json.dumps(EXTRA_BRIDGES, indent=4)}\n\n"
    
    # Add new bridge configuration
    output += "# New bridge configuration\n"
    output += f"BRIDGES = {json.dumps(new_bridges, indent=4)}\n"
    
    # Write to a new config file
    with open("new_config.py", "w") as f:
        f.write(output)
    
    print("Migration complete! New configuration written to new_config.py")
    print("Review the file and rename it to config.py when ready to use.")

if __name__ == "__main__":
    migrate_extra_bridges_to_new_format()
